name: CI/CD with Terraform

on:
  push:
    branches:
      - Complete-CI/CD-with-Terraform-AZURE

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:  # Définir des variables d'environnement globales
      AZURE_ACCESS_KEY_ID: ${{ secrets.AZURE_ACCESS_KEY_ID }}
      AZURE_ACCESS_KEY_SECRET: ${{ secrets.AZURE_ACCESS_KEY_SECRET }}
      AZURE_SSH_KEY_PRIVATE: ${{ secrets.AZURE_SSH_KEY_PRIVATE }}
      AZURE_SSH_KEY_PUBLIC: ${{ secrets.AZURE_SSH_KEY_PUBLIC }}
      AZURE_TF_STATE_BUCKET_NAME: ${{ secrets.AZURE_TF_STATE_BUCKET_NAME }}
      AZURE_REGION: "eastus"

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.0  # Vérifiez la version ici
        with:
          terraform_version: 1.1.7 # Mettez à jour la version si nécessaire

      - name: Terraform Init
        run: |
          cd terraform 
          terraform init

      - name: List files
        run: cd terraform && ls -la

      - name: Terraform Apply
        run: |
          cd terraform 
          terraform apply -auto-approve
