name: CI/CD with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:  # Définir des variables d'environnement globales
      AZURE_ACCESS_KEY_ID: ${{ secrets.AZURE_ACCESS_KEY_ID }}
      AZURE_ACCESS_KEY_SECRET: ${{ secrets.AZURE_ACCESS_KEY_SECRET }}
      AZURE_SSH_KEY_PRIVATE: ${{ secrets.AZURE_SSH_KEY_PRIVATE }}
      AZURE_SSH_KEY_PUBLIC: ${{ secrets.AZURE_SSH_KEY_PUBLIC }}
      AZURE_TF_STATE_BUCKET_NAME: ${{ secrets.AZURE_TF_STATE_BUCKET_NAME }}
      AZURE_REGION: "eastus"


    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7 # Mettez à jour la version si nécessaire

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

